base: /Python-Level-0/
description: League Level0 Python
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /intro
    title: Introduction
  - children:
    - path: /lessons/turtles/meet-tina/
      title: Meet Tina
    - path: /lessons/turtles/moving/
      title: Moving
    - path: /lessons/turtles/color/
      title: Color
    - path: /lessons/turtles/saying-hello/
      title: Saying Hello
    - path: /lessons/turtles/tinas-pen/
      title: Tinas Pen
    - path: /lessons/turtles/going-in-circles/
      title: Going In Circles
    - path: /lessons/turtles/tinas-grid/
      title: Tinas Grid
    - path: /lessons/turtles/shapes-and-colors/
      title: Shapes And Colors
    collapsable: false
    path: /lessons/turtles/
    title: Turtles
  - children:
    - path: /lessons/loops/variables/
      title: Variables
    - path: /lessons/loops/loops/
      title: Make a Square with Loops
    - path: /lessons/loops/functions/
      title: Functions
    - path: /lessons/loops/make-5-cakes/
      title: Make 5 Cakes
    - path: /lessons/loops/crazy_shapes/
      title: Crazy Shapes
    collapsable: false
    path: /lessons/loops/
    title: Remembering,  Repeating
title: League Level0 Python
