base: /Python-Level-0/
description: League Level0 Python
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /intro
    title: Introduction
  - children:
    - path: /lessons/turtles/meet-tina/
      title: Meet Tina
    - path: /lessons/turtles/moving/
      title: Moving
    - path: /lessons/turtles/color/
      title: Color
    - path: /lessons/turtles/saying-hello/
      title: Saying Hello
    - path: /lessons/turtles/tinas-pen/
      title: Tinas Pen
    - path: /lessons/turtles/going-in-circles/
      title: Going In Circles
    - path: /lessons/turtles/tinas-grid/
      title: Tinas Grid
    collapsable: false
    path: /lessons/turtles/
    title: Turtles
  - children:
    - path: /lessons/module1/var_loop_list/
      title: Variables Loops and Lists
    - path: /lessons/module1/variables/
      title: Variables
    - path: /lessons/module1/loops/
      title: Make a Square with Loops
    - path: /lessons/module1/functions/
      title: Functions
    - path: /lessons/module1/crazy_shapes/
      title: Crazy Shapes
    - path: /lessons/module1/first_look_at_lists/
      title: First Look at Lists
    - path: /lessons/module1/if_and_else/
      title: Making Choices with If and Else
    collapsable: false
    path: /lessons/module1/
    title: 'Module 1: Remembering and Repeating'
  - children:
    - path: /lessons/module2/more_functions/
      title: More Functions
    - path: /lessons/module2/happy_pet/
      title: Happy Pet
    - path: /lessons/module2/obedient_turtle/
      title: Obedient Turtle
    - path: /lessons/module2/houses/
      title: Drawing Houses
    collapsable: false
    path: /lessons/module2/
    title: 'Module 2: Function Practice'
  - children:
    - path: /lessons/module3/more_lists/
      title: Iterating over Iterables
    - path: /lessons/module3/yet_more_lists/
      title: Unpacking Tuples
    collapsable: false
    path: /lessons/module3/
    title: 'Module 3: Lists, Strings, and Iterables'
  - children:
    - path: /lessons/project/level0_project/
      title: Level 0 Project
    collapsable: false
    title: Final Project
title: League Level0 Python
